macro(pl_configure_includes TARGET_NAME TARGET_INCLUDES)
    if(NOT "${TARGET_INCLUDES}" STREQUAL "")
        target_include_directories(${TARGET_NAME} PUBLIC ${TARGET_INCLUDES})
    else()
        message(VERBOSE "[${TARGET_NAME}] Note: No include directory provided")
    endif()
endmacro()

macro(pl_configure_libraries TARGET_NAME TARGET_LIBRARIES)
    if(NOT "${TARGET_LIBRARIES}" STREQUAL "")
        target_link_libraries(${TARGET_NAME} PUBLIC ${TARGET_LIBRARIES})
    else()
        message(VERBOSE "[${TARGET_NAME}] Note: No dependencies provided")
    endif()
endmacro()

function(pl_add_lib LIBRARY_NAME LIBRARY_SOURCES LIBRARY_INCLUDES LIBRARY_DEPENDENCIES)
    add_library(${LIBRARY_NAME} STATIC ${LIBRARY_SOURCES})
    pl_configure_includes("${LIBRARY_NAME}" "${LIBRARY_INCLUDES}")
    pl_configure_libraries("${LIBRARY_NAME}" "${LIBRARY_DEPENDENCIES}")
endfunction()

function(pl_add_test TEST_NAME TEST_SOURCES TEST_INCLUDES TEST_LIBRARIES)
    add_executable(${TEST_NAME} ${TEST_SOURCES})
    pl_configure_includes("${TEST_NAME}" "${TEST_INCLUDES}")
    pl_configure_libraries("${TEST_NAME}" "${TEST_LIBRARIES};GTest::gtest;GTest::gtest_main")
    gtest_discover_tests(${TEST_NAME})
endfunction()